name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.3.1"]
        ghc: ["8.8.3"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            ./.stack-work
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ hashFiles('**/stack.yaml.lock') }}

      - name: Run Tests
        uses: actions/setup-haskell@v1.1
        with:
          enable-stack: true
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}
        run: |  # It's important to regenerate the classifiers after updating the code and before running the test suite.
          stack build :duckling-regen-exe && stack exec duckling-regen-exe && stack test
