name: Release

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      # Checkout the latest version of the code from default branch.
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image and push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: chemondis/duckling
          IMAGE_TAG: ${GITHUB_REF##*/}
        # Run the build and then push to ECR here
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
